#!/bin/sh
while read file
do
    if [ ! -e "$file" ]; then
        wget "https://github.com/mozilla/Fira/raw/master/otf/${file}"
    fi
done <<EOF
FiraMono-Bold.otf
FiraMono-Medium.otf
FiraMono-Regular.otf
FiraSans-Bold.otf
FiraSans-BoldItalic.otf
FiraSans-Book.otf
FiraSans-BookItalic.otf
FiraSans-Eight.otf
FiraSans-EightItalic.otf
FiraSans-ExtraBold.otf
FiraSans-ExtraBoldItalic.otf
FiraSans-ExtraLight.otf
FiraSans-ExtraLightItalic.otf
FiraSans-Four.otf
FiraSans-FourItalic.otf
FiraSans-Hair.otf
FiraSans-HairItalic.otf
FiraSans-Heavy.otf
FiraSans-HeavyItalic.otf
FiraSans-Italic.otf
FiraSans-Light.otf
FiraSans-LightItalic.otf
FiraSans-Medium.otf
FiraSans-MediumItalic.otf
FiraSans-Regular.otf
FiraSans-SemiBold.otf
FiraSans-SemiBoldItalic.otf
FiraSans-Thin.otf
FiraSans-ThinItalic.otf
FiraSans-Two.otf
FiraSans-TwoItalic.otf
FiraSans-Ultra.otf
FiraSans-UltraItalic.otf
FiraSans-UltraLight.otf
FiraSans-UltraLightItalic.otf
FiraSansCondensed-Bold.otf
FiraSansCondensed-BoldItalic.otf
FiraSansCondensed-Book.otf
FiraSansCondensed-BookItalic.otf
FiraSansCondensed-Eight.otf
FiraSansCondensed-EightItalic.otf
FiraSansCondensed-ExtraBold.otf
FiraSansCondensed-ExtraLight.otf
FiraSansCondensed-ExtraLightItalic.otf
FiraSansCondensed-ExtraboldItalic.otf
FiraSansCondensed-Four.otf
FiraSansCondensed-FourItalic.otf
FiraSansCondensed-Hair.otf
FiraSansCondensed-HairItalic.otf
FiraSansCondensed-Heavy.otf
FiraSansCondensed-HeavyItalic.otf
FiraSansCondensed-Italic.otf
FiraSansCondensed-Light.otf
FiraSansCondensed-LightItalic.otf
FiraSansCondensed-Medium.otf
FiraSansCondensed-MediumItalic.otf
FiraSansCondensed-Regular.otf
FiraSansCondensed-SemiBold.otf
FiraSansCondensed-SemiboldItalic.otf
FiraSansCondensed-Thin.otf
FiraSansCondensed-ThinItalic.otf
FiraSansCondensed-Two.otf
FiraSansCondensed-TwoItalic.otf
FiraSansCondensed-Ultra.otf
FiraSansCondensed-UltraItalic.otf
FiraSansCondensed-UltraLight.otf
FiraSansCondensed-UltraLightItalic.otf
EOF
